version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./../data/elasticsearch/data:/data
      - ./../data/elasticsearch/logs:/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./../data/logstash/conf.d:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5000:5000/udp"
    networks:
      - docker_elk
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "80:5601"
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
